version: '3'

services:
  jaeger-demo:
    image: jaeger-demo-image:latest
    ports:
      - "8105:8105"
    depends_on:
      - demosql

  demosql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: helloworld
      MYSQL_DATABASE: jaegerdemo
    ports:
      - "3308:3306"

  jaeger:
    image: jaegertracing/all-in-one:1.18
    ports:
      - "5775:5775/udp"
      - "6831:6831/udp"
      - "6832:6832/udp"
      - "5778:5778"
      - "16686:16686"
      - "14268:14268"
      - "14250:14250"
      - "9411:9411"
    depends_on:
      - jaeger-demo
